### ISSUE TITLE
Asset store should attempt remote servers even if the local storage is full

### ISSUE THREAD

**Issue by kf6kjg** [kf6kjg/WHIP-LRU#10]
Assuming of course that there are upstream servers.  If not, or if the remote servers all fail or reject, the client should be informed of the error.

**Comment by appurist** [comment]
Good point, the local storage is still a cache, even if it is very important (like the primary central one for a grid).

**Comment by kf6kjg** [comment]
Moved to https://github.com/kf6kjg/chattel/issues/6 as it's not a WHIP-LRU issue.  When that resolves this can be revisited.
