### ISSUE TITLE
Adding a new item to the LMDB cache goes into infinite loop when db is full

### ISSUE THREAD

**Issue by kf6kjg** [kf6kjg/WHIP-LRU#11]
This is because LMDB doesn't actually make the space of a deleted record available for a new record - at least while the DB is open.  From what I've read it might make it available upon normal shutdown.

The problem is that I've no good solution thus far and this is blocking the system from actually working: the degenerate case of having a full DB is expected to be the normal working conditions of this application.  It needs to be able to remove items and have enough room to store new items.

Testing of the issues involved has been committed to https://github.com/kf6kjg/WHIP-LRU/tree/LMDBtesting

You can watch the action while debugging via the following BASH snippet, assuming you have `lmdb-utils` installed:
```
cd bin
while true; do clear; mdb_stat -a test_ac_lmdb/; ll test_ac_lmdb/data.mdb; sleep 0.5; done
```

I've added code to the branch to try only 5 times and then jump out of the loop, but that's a bad hack.

**Comment by appurist** [comment]
Could you define 'db is full'? If this refers to the available disk space on the drive, it is an important part of the engineering to not push it right to the limit, but rather leave a certain amount of space free for OS and application use (e.g. log files), paging, etc.

If this refers to some kind of internal LMDB issue, presumably they have some mechanism for audit, that dbs do not just grow and never shrink even when data is deleted.  If the use of LMDB introduces new garbage collection-like issues, we can't afford a large dropout to run a db GC, and LMDB may not be suitable for this use case. (!)

**Comment by kf6kjg** [comment]
"DB is full" means that the size of the DB file has reached the specified, configured, maximum.  Nothing to do with disk space - that's a different situation.

My correction for this has been to temporally partition the DBs while keeping track of their disk space.  This should solve both this issue and several others, most of which don't have GitHub issues tracking them.

**Comment by kf6kjg** [comment]
With the changeover to the temporally partitioned local storage engine this has been resolved.
